/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as WeatherForecastRouteImport } from './routes/weather-forecast';
import { Route as IndexRouteImport } from './routes/index';

const WeatherForecastRoute = WeatherForecastRouteImport.update({
  id: '/weather-forecast',
  path: '/weather-forecast',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/weather-forecast': typeof WeatherForecastRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/weather-forecast': typeof WeatherForecastRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/weather-forecast': typeof WeatherForecastRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/weather-forecast';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/weather-forecast';
  id: '__root__' | '/' | '/weather-forecast';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  WeatherForecastRoute: typeof WeatherForecastRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather-forecast': {
      id: '/weather-forecast';
      path: '/weather-forecast';
      fullPath: '/weather-forecast';
      preLoaderRoute: typeof WeatherForecastRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WeatherForecastRoute: WeatherForecastRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
